/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WasmDemoRouteImport } from './routes/wasm-demo'
import { Route as IndexRouteImport } from './routes/index'

const WasmDemoRoute = WasmDemoRouteImport.update({
  id: '/wasm-demo',
  path: '/wasm-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wasm-demo': typeof WasmDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wasm-demo': typeof WasmDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wasm-demo': typeof WasmDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wasm-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wasm-demo'
  id: '__root__' | '/' | '/wasm-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WasmDemoRoute: typeof WasmDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wasm-demo': {
      id: '/wasm-demo'
      path: '/wasm-demo'
      fullPath: '/wasm-demo'
      preLoaderRoute: typeof WasmDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WasmDemoRoute: WasmDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
